### ISSUE TITLE
Panel throws "kirby is not defined" when plugin is enabled. 

### ISSUE THREAD

**Issue by trashbytes** [jenstornell/kirby-plugin-installer#7]
I am using latest Kirby 2.5.5. I encountered the same problem with another plugin.

**Comment by jenstornell** [comment]
What other plugin?

**Comment by trashbytes** [comment]
Kirby Cache Widgets

**Comment by trashbytes** [comment]
I am an idiot.

**Comment by jenstornell** [comment]
@trashbytes Was it your fault? Would you mind telling me what you did wrong? :smile:

**Comment by trashbytes** [comment]
Yes! I was in the middle of installing some **widgets** which made me ignore the readme, 'cause I thought "well that is easy", so I installed this as a widget in the wrong directory..
Shame on me!
